ShopWatchFinal/ShopWatch.WebMvc/Controllers/SearchController.cs
using ShopWatch.BussinessLogicLayer.IService;
using ShopWatch.WebMvc.ViewModels.Customer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace ShopWatch.WebMvc.Controllers
{
	public class SearchController : Controller
	{
		private readonly ICategoryService _categoryServices;

		private readonly IPublisherService _publisherServices;

		public SearchController(
			ICategoryService categoryServices,

			IPublisherService publisherServices)
		{
			_categoryServices = categoryServices;

			_publisherServices = publisherServices;
		}

		public ActionResult CategorySearch()
		{
			var syncContext = SynchronizationContext.Current;
			SynchronizationContext.SetSynchronizationContext(null);
			var categories = _categoryServices.GetAsync(orderBy: c => c.OrderBy(x => x.CategoryName), page: 1, pageSize: 3);
			SynchronizationContext.SetSynchronizationContext(syncContext);

			return PartialView(categories);
		}



		public ActionResult PublisherSearch()
		{
			var syncContext = SynchronizationContext.Current;
			SynchronizationContext.SetSynchronizationContext(null);
			var publishers = _publisherServices.GetAsync(orderBy: p => p.OrderBy(x => x.PublisherName));
			SynchronizationContext.SetSynchronizationContext(syncContext);
			return PartialView(publishers);
		}

		public ActionResult PriceSearch()
		{
			var priceSearchItems = new List<PriceSearchItem>
			{
				new PriceSearchItem()
				{
					DisplayValue =1000000,
					ActionValue = 1000000,

				},
				new PriceSearchItem()
				{
					DisplayValue = 5000000,
					ActionValue = 5000000,

				},
				new PriceSearchItem()
				{
					DisplayValue = 10000000,
					ActionValue = 10000000,

				},
				new PriceSearchItem()
				{
					DisplayValue = 20000000,
					ActionValue = 20000000,

				}
			};

			return PartialView(priceSearchItems);
		}
	}

}

ShopWatchFinal/ShopWatch.WebMvc/Controllers/WatchController.cs
using ShopWatch.BussinessLogicLayer;
using ShopWatch.BussinessLogicLayer.IService;
using ShopWatch.Model;
using ShopWatch.WebMvc.ViewModels.Customer;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ShopWatch.WebMvc.Controllers
{
	public class WatchController : Controller
	{
		private readonly IWatchService _watchServices;
		public WatchController(IWatchService watchServices)
		{
			_watchServices = watchServices;
		}
		public ActionResult ListByCategory(string category)
		{
			IEnumerable<Watch> watches;
			string currentCategory = string.Empty;

			if (category.IsBlank())
			{
				watches = _watchServices.GetAsync(orderBy: b => b.OrderBy(x => x.WatchName), page: 1, pageSize: 10);
				currentCategory = "All of Watches";
			}
			else
			{
				watches = _watchServices.GetAsync(filter: b => b.Category.CategoryName == category, orderBy: b => b.OrderBy(x => x.WatchName), page: 1, pageSize: 10);
				currentCategory = category;
			}

			return View(new WatchListByCategoryViewModel
			{
				Watches = watches,
				CurrentCategory = currentCategory
			});
		}

		public ActionResult ListByPublisher(string publisher)
		{
			IEnumerable<Watch> watches;
			string currentPublisher = string.Empty;

			if (publisher.IsBlank())
			{
				watches = _watchServices.GetAsync(orderBy: b => b.OrderBy(x => x.WatchName), page: 1, pageSize: 100);
				currentPublisher = "All of Watches";
			}
			else
			{
				watches = _watchServices.GetAsync(filter: b => b.Publisher.PublisherName == publisher, orderBy: b => b.OrderBy(x => x.WatchName), page: 1, pageSize: 100);
				currentPublisher = publisher;
			}

			return View(new WatchListByPublisherViewModel
			{
				Watches = watches,
				CurrentPublisher = currentPublisher
			});
		}
		public  ActionResult ListByPrice(decimal priceLevel)
		{
			IEnumerable<Watch> watches;
			decimal currentPrice = decimal.Zero;

			if (priceLevel < 0)
			{
				watches = _watchServices.GetAsync(orderBy: b => b.OrderBy(x => x.WatchName), page: 1, pageSize: 100);
				currentPrice = 0;
			}
			else
			{
				watches = _watchServices.GetAsync(filter: b => b.Price < priceLevel, orderBy: b => b.OrderBy(x => x.WatchName), page: 1, pageSize: 100);

				currentPrice = priceLevel;
			}

			return View(new WatchListByPriceViewModel
			{
				Watches = watches,
				CurrentPrice = currentPrice
			});
		}
		public ActionResult Details(int id)
		{
			var watch =  _watchServices.GetById(id);
			if (watch == null)
				return HttpNotFound();
			return View(watch);
		}
	}
}

ShopWatchFinal/ShopWatch.WebMvc/Views/Search/CategorySearch.cshtml
@using ShopWatch.Model
@model IEnumerable<Category>

<div id="submenu1" class="collapse sidebar-submenu">
	@foreach (var item in Model)
	{
<a href="@Url.Action("ListByCategory", "Watch", new { category=item.CategoryName })" class="list-group-item list-group-item-action bg-info text-white">
	<span class="fas fa-swatchbook mr-1"></span>
	<span class="menu-collapsed">@item.CategoryName</span>
</a>}
</div>

ShopWatchFinal/ShopWatch.WebMvc/Views/Search/PriceSearch.cshtml
@using ShopWatch.WebMvc.ViewModels.Customer
@using System.Globalization
@model IEnumerable<PriceSearchItem>

<div id="submenu4" class="collapse sidebar-submenu">
	@foreach (var item in Model)
	{
		<a href="@Url.Action("ListByPrice", "Watch", new { priceLevel=item.ActionValue })" class="list-group-item list-group-item-action bg-info text-white">
			<span class="fas fa-dollar-sign mr-1"></span>
			<span class="menu-collapsed">@item.DisplayValue.ToString("C0", CultureInfo.CreateSpecificCulture("vi-VN"))</span>
		</a>}
</div>

ShopWatchFinal/ShopWatch.WebMvc/Views/Search/PublisherSearch.cshtml
@using ShopWatch.Model
@model IEnumerable<Publisher>

<div id="submenu3" class="collapse sidebar-submenu">
	@foreach (var item in Model)
	{
<a href="@Url.Action("ListByPublisher", "Watch", new { publisher=item.PublisherName })" class="list-group-item list-group-item-action bg-info text-white">
	<span class="fas fa-building mr-1"></span>
	<span class="menu-collapsed">@item.PublisherName</span>
</a>}
</div>