ShopWatchFinal/ShopWatch.WebMvc/Areas/Admin/Controllers/WatchPromotionManagementController.cs
using ShopWatch.BussinessLogicLayer.IService;
using ShopWatch.Model;
using ShopWatch.Model.DataContext;
using ShopWatch.WebMvc.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ShopWatch.WebMvc.Areas.Admin.Controllers
{
	public class WatchPromotionManagementController : Controller
    {
        private readonly IPromotionService _promotionService;
        private readonly IWatchService _watchService;
        private readonly ShopWatchDataContext _context;

        public WatchPromotionManagementController(IPromotionService promotionService,IWatchService watchService,ShopWatchDataContext context)
		{
            _promotionService = promotionService;
            _watchService = watchService;
            _context = context;
		}
        public ActionResult Index()
        {
            var listPromotion = _promotionService.GetAll();
            return View(listPromotion);
        }
        public ActionResult AddWatchPromotion()
        {
            var haiz = new WatchPromotionViewModel();
            List<Promotion> promotions = _promotionService.GetAll().ToList();
			foreach (var item in promotions)
			{
                if (item.EndDate < DateTime.Now) promotions.Remove(item); 
			}
            ViewBag.promotions = new SelectList(promotions.OrderBy(x => x.Percent), "PromotionId", "PromotionName");
            List<Watch> watches = _watchService.GetAll().ToList();
            ViewBag.watches = new SelectList(watches.OrderBy(x => x.WatchId), "WatchId", "WatchName");
            return View(haiz);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult AddWatchPromotion(WatchPromotionViewModel a)
        {
            if (!ModelState.IsValid)
            {
                return View(a);
            }
            var watchpromotion = _promotionService.GetById(a.PromotionId);
            var watch = _watchService.GetById(a.WatchId);
            watchpromotion.Watches.Add(watch);
            _promotionService.Update(watchpromotion);

            var ui = watch.Promotions.FirstOrDefault();
            if(watchpromotion.StartDate<=DateTime.Now && DateTime.Now<=watchpromotion.EndDate)
			{
                watch.PricePromotion = watch.Price - (watch.Price * ui.Percent) / 100;
            }
            _watchService.Update(watch);
            //string mn = "";
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult DeleteWatchPromotion(int id,int id2)
        {
            var a = _watchService.GetById(id);
            var b = _promotionService.GetById(id2);
            b.Watches.Remove(a);
            _promotionService.Update(b);
            a.PricePromotion = a.Price;
            _watchService.Update(a);
            return RedirectToAction("Index");
        }
    }
}

ShopWatchFinal/ShopWatch.WebMvc/Areas/Admin/Views/WatchPromotionManagement/AddWatchPromotion.cshtml
@using ShopWatch.WebMvc.ViewModels
@model WatchPromotionViewModel
@{
    ViewBag.Title = "AddWatchPromotion";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<h2>Add WatchPromotion</h2>
<hr />
<form action="/Admin/WatchPromotionManagement/AddWatchPromotion" method="post" class="row form-horizontal" enctype="multipart/form-data">
	@Html.AntiForgeryToken()
	<div class="col">
		<div class="form-group">
			<label class="control-label">Sản phẩm:&nbsp;</label>
			<div class="input-group mb-3">
				@Html.DropDownListFor(m => m.WatchId, new SelectList(ViewBag.watches, "Value", "Text"), "--  Vui lòng chọn sản phẩm  --", new { @class = "form-control", @id = "CateList" })
				@Html.ValidationMessageFor(m => m.WatchId, "", new { @class = "text-danger" })
			</div>
		</div>
	</div>
	<div class="col">
		<div class="form-group">
			<label class="control-label">Khuyến mãi:&nbsp;</label>
			<div class="input-group mb-3">
				@Html.DropDownListFor(m => m.PromotionId, new SelectList(ViewBag.promotions, "Value", "Text"), "--  Vui lòng chọn khuyến mãi  --", new { @class = "form-control", @id = "AutList" })
				@Html.ValidationMessageFor(m => m.PromotionId, "", new { @class = "text-danger" })
			</div>
		</div>
	</div>
	<div class="col-12 ">
		<div class="form-group">
			<input type="submit" class="btn btn-primary" value="Thêm" />
			<a href="/Admin/WatchPromotionManagement" class="btn btn-secondary">Quay lại</a>
		</div>
	</div>
</form>

ShopWatchFinal/ShopWatch.WebMvc/Areas/Admin/Views/WatchPromotionManagement/Index.cshtml
@using System.Collections.Generic
@using ShopWatch.Model
@model IEnumerable<Promotion>
@{
	ViewBag.Title = "Index";
	Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Danh sách sản phẩm khuyến mãi</h2>
<a href="@Url.Action("AddWatchPromotion", "WatchPromotionManagement")" class="btn btn-primary float-left">Thêm</a>
<br/>
<br />
<table class="table table-condensed ">
	<tr class="d-flex">
		<th class="col-md-3 text-center">Tên khuyến mãi</th>
		<th class="col-md-3 text-center">Sản phẩm áp dụng</th>
		<th class="col-md-2 text-center">Ngày bắt đầu</th>
		<th class="col-md-2 text-center">Ngày kết thúc</th>
		<th class="col-md-1 text-center">Phần trăm</th>
		<th class="col-md-1 text-center"></th>
	</tr>

	@foreach (var watch in Model)
	{
		<tr class="d-flex">
			<td class="col-md-3 text-center">
				@watch.PromotionName
			</td>
			@if (watch.Watches!=null)
			{
				<td class="col-md-3 text-center">
					@foreach (var item in watch.Watches)
					{
						<p><a href="@Url.Action("Details", "WatchMangement", new { id = item.WatchId, area = "Admin" })">@item.WatchName</a></p>
					}
				</td>
				<td class="col-md-2 text-center">
					@watch.StartDate.ToString("dd/MM/yyyy")
				</td>
				<td class="col-md-2 text-center">
					@watch.EndDate.ToString("dd/MM/yyyy")
				</td>
				<td class="col-md-1">
					@watch.Percent %
				</td>
				<td class="col-md-1 text-center">
					@foreach (var item in watch.Watches)
					{
						<form action="@Url.Action("DeleteWatchPromotion", "WatchPromotionManagement", new { id = item.WatchId, id2 = watch.PromotionId })" method="post">
							<button type="submit" onclick="return confirm('Are you sure to delete this?');" class="btn btn-danger">Delete</button>
						</form>
					}
				</td>
			}
		</tr>
	}
</table>