ShopWatchFinal/ShopWatch.WebMvc/Areas/Admin/Controllers/WatchMangementController.cs
using AutoMapper;
using ShopWatch.BussinessLogicLayer;
using ShopWatch.BussinessLogicLayer.IService;
using ShopWatch.BussinessLogicLayer.Services;
using ShopWatch.Model;
using ShopWatch.Model.DataContext;
using ShopWatch.WebMvc.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;
namespace ShopWatch.WebMvc.Areas.Admin.Controllers
{
	public class WatchMangementController : Controller
    {
        private readonly IWatchService _watchService;
        private readonly ShopWatchDataContext _context = new ShopWatchDataContext();
        private readonly ICategoryService _categoryService;
        private readonly IPublisherService _publisherService;

        public WatchMangementController(IWatchService watchService, ICategoryService categoryService, IPublisherService publisherService)
        {
            _watchService = watchService;
            _categoryService = categoryService;
            _publisherService = publisherService;
            
        }
        public ActionResult Index(string sortOrder, string currentFilter,
           string searchString, int? page)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = sortOrder.IsBlank() ? "name_desc" : "";
            ViewData["QuantitySortParm"] = sortOrder == "Quantity" ? "quantity_desc" : "Quantity";
            ViewData["PriceSortParm"] = sortOrder == "Price" ? "price_desc" : "Price";
            ViewData["PricePromotionSortParm"] = sortOrder == "PricePromotion" ? "pricepromotiont_desc" : "PricePromotion";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            Expression<Func<Watch, bool>> filter = null;
            Func<IQueryable<Watch>, IOrderedQueryable<Watch>> orderBy = null;

            if (searchString.IsNotBlank())
            {
                filter = a => a.WatchName.Contains(searchString);
            }
            switch (sortOrder)
            {
                case "":
                    orderBy = b => b.OrderBy(s => s.WatchName);
                    break;
                case "name_desc":
                    orderBy = b => b.OrderByDescending(s => s.WatchName);
                    break;
                case "Quantity":
                    orderBy = b => b.OrderBy(s => s.Quantity);
                    break;
                case "quantity_desc":
                    orderBy = b => b.OrderByDescending(s => s.Quantity);
                    break;
                case "Price":
                    orderBy = b => b.OrderBy(s => s.Price);
                    break;
                case "price_desc":
                    orderBy = b => b.OrderByDescending(s => s.Price);
                    break;
                case "PricePromotion":
                    orderBy = b => b.OrderBy(s => s.PricePromotion);
                    break;
                case "pricepromotion_desc":
                    orderBy = b => b.OrderByDescending(s => s.PricePromotion);
                    break;
                
                default:
                    orderBy = b => b.OrderBy(s => s.Quantity);
                    break;
            }

            var Watchs = _watchService.GetAsync(filter: filter, orderBy: orderBy, page: page ?? 1, pageSize: 10);
            #region Cập nhật giá khuyến mãi của sản phẩm khi không có khuyến mãi nào đang được áp dụng
            var watches = _context.Watches.ToList();
            foreach (var item in watches)
            {
                if (item.Promotions.Count() == 0)
                {
                    item.PricePromotion = item.Price;
                }
                foreach (var i in item.Promotions)
                {
                    if (i.EndDate < DateTime.Now || i.StartDate>DateTime.Now)
                    {
                        item.PricePromotion = item.Price;
                    }
                }
                _context.Watches.AddOrUpdate(item);
                _context.SaveChanges();
            }
            #endregion

            return View(Watchs);
        }
        public ActionResult Details(int id)
        {
            var user = _watchService.GetById(id);
            var watchViewModel = Mapper.Map<WatchViewModel>(user);
            return View(watchViewModel);
        }
        public ActionResult AddWatch()
        {
            var watchEditViewModel = new WatchEditViewModel();
            
            List<Category> categories =  _categoryService.GetAsync(orderBy: x => x.OrderBy(b => b.CategoryName), page: 1, pageSize: 10);
            ViewBag.Categories = new SelectList(categories.OrderBy(x => x.CategoryId), "CategoryId", "CategoryName");
            List<Publisher> publishers =  _publisherService.GetAsync(orderBy: x => x.OrderBy(b => b.PublisherName), page: 1, pageSize: 10);
            ViewBag.Publishers = new SelectList(publishers.OrderBy(x => x.PublisherId), "PublisherId", "PublisherName");
            return View(watchEditViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult AddWatch(WatchEditViewModel watchEditViewModel,HttpPostedFileBase Img,
            HttpPostedFileBase small1, HttpPostedFileBase small2, HttpPostedFileBase small3)
        {
            if (!ModelState.IsValid)
            {
                var watch = Mapper.Map<Watch>(watchEditViewModel);
                string fileName = "";
				int id = _context.Watches.ToList().Last().WatchId + 1;
                watch.SmallImage = "SP"+id;
                if (Img != null && Img.ContentLength > 0)
                {
                    try
                    {
                        int index = Img.FileName.IndexOf(".");
                        fileName = "SP000" + id.ToString() + "." + Img.FileName.Substring(index + 1);
                        string path = Path.Combine(Server.MapPath("~/Assets/images/HINHLON"), fileName);
                        Img.SaveAs(path);
                    }
                    catch (Exception)
                    {
                        throw;
                    }
                }
                if (small1 != null && small1.ContentLength > 0)
                {

					try
					{
						string path = Path.Combine(Server.MapPath("~/Assets/images/HINHNHO/" + watch.SmallImage), "1.jpg");
						small1.SaveAs(path);
					}
					catch (Exception)
					{

						throw;
					}
                }
                if (small3 != null && small3.ContentLength > 0)
                {

					try
					{
						string path = Path.Combine(Server.MapPath("~/Assets/images/HINHNHO/" + watch.SmallImage), "3.jpg");
						small3.SaveAs(path);
					}
					catch (Exception)
					{

						throw;
					}


                }
                if (small2 != null && small2.ContentLength > 0)
                {

					try
					{
						string path = Path.Combine(Server.MapPath("~/Assets/images/HINHNHO/" + watch.SmallImage), "2.jpg");
						small2.SaveAs(path);
					}
					catch (Exception)
					{

						throw;
					}
                }

                watch.CreatedDate = DateTime.Now;
                watch.ModifiedDate = DateTime.Now;
                watch.ImageUrl = fileName;
                watch.PricePromotion = watchEditViewModel.Price;
                _watchService.Create(watch);

                return RedirectToAction("Index");
            }
            return View(watchEditViewModel);
        }
        public ActionResult EditWatch(int id)
        {
            List<Category> categories = _categoryService.GetAsync(orderBy: x => x.OrderBy(b => b.CategoryName), page: 1, pageSize: 100);
            ViewBag.Categories = new SelectList(categories.OrderBy(x => x.CategoryId), "CategoryId", "CategoryName");
            List<Publisher> publishers = _publisherService.GetAsync(orderBy: x => x.OrderBy(b => b.PublisherName), page: 1, pageSize: 100);
            ViewBag.Publishers = new SelectList(publishers.OrderBy(x => x.PublisherId), "PublisherId", "PublisherName");
            var watch = _watchService.GetById(id);
            if (watch == null)
            {
                return HttpNotFound();
            }
            

            return View(watch);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult EditWatch(Watch watche,HttpPostedFileBase Img,
            HttpPostedFileBase small1, HttpPostedFileBase small2, HttpPostedFileBase small3)
        {
           
            if (!ModelState.IsValid)
            {
                var watch = _watchService.GetById(watche.WatchId);
                string fileName = "";

                int id = _context.Watches.ToList().Last().WatchId + 1;
                if (Img != null && Img.ContentLength > 0)
                {
                    try
                    {
                        int index = Img.FileName.IndexOf(".");
                        fileName = "SP000" + id.ToString() + "." + Img.FileName.Substring(index + 1);
                        string path = Path.Combine(Server.MapPath("~/Assets/images/HINHLON"), fileName);
                        Img.SaveAs(path);
                    }
                    catch (Exception)
                    {
                        throw;
                    }
                }
                if (small1 != null && small1.ContentLength > 0)
                {

                    try
                    {
                        string path = Path.Combine(Server.MapPath("~/Assets/images/HINHNHO/" + watch.SmallImage), "1.jpg");
                        small1.SaveAs(path);
                    }
                    catch (Exception)
                    {

                        throw;
                    }

ShopWatchFinal/ShopWatch.WebMvc/Areas/Admin/Views/WatchMangement/AddWatch.cshtml
@using ShopWatch.WebMvc.ViewModels
@model WatchEditViewModel
@{ ViewBag.Title = "AddWatch";
	Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml"; }
<h2>Add Watch</h2>
<hr />
<form action="/Admin/WatchMangement/AddWatch" method="post" class="row form-horizontal" enctype="multipart/form-data">
	@Html.AntiForgeryToken()
	<div class="col">
		<div class="form-group">
			<label name="Name" class="control-label">Watch Name:</label>
			<div>
				<input type="text" name="WatchName" class="form-control" value="@Model.WatchName" required />
				@Html.ValidationMessageFor(m => m.WatchName, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			<label class="control-label">Description:</label>
			<div>
				<textarea class="form-control" name="Description" id="ckeditor" required></textarea>
				@Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			<label class="control-label">Evaluate:</label>
			<div>
				<textarea class="form-control" name="Evaluate" id="ckeditor2" required></textarea>
				@Html.ValidationMessageFor(m => m.Evaluate, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			<label class="control-label">Price:</label>
			<div>
				<input type="number" class="form-control" name="Price" min="1" />
				@Html.ValidationMessageFor(m => m.Price, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			<label class="control-label">Quantity:</label>
			<div>
				<input type="number" class="form-control" name="Quantity" min="1" />
				@Html.ValidationMessageFor(m => m.Quantity, "", new { @class = "text-danger" })
			</div>
		</div>
	</div>
	<div class="col">
		<div class="form-group">
			<label class="control-label">Category:</label>
			<div class="input-group mb-3">
				@Html.DropDownListFor(m => m.CategoryId, new SelectList(ViewBag.Categories, "Value", "Text"), "Select a category", new { @class = "form-control", @id = "CateList" })
			</div>
		</div>

		<div class="form-group">
			<label class="control-label">Publisher:</label>
			<div class="input-group mb-3">
				@Html.DropDownListFor(m => m.PublisherId, new SelectList(ViewBag.Publishers, "Value", "Text"), "Select an author", new { @class = "form-control", @id = "AutList" })
			</div>
		</div>

		<div class="form-group">
			<label class="control-label" for="ImgUrl">Image:</label>
			<div class="form-row">
				<div class="col-6">
					<input type="file" class="custom-file-input" id="validatedCustomFile" name="Img" onchange="readURL(this)" required>
					<label class="custom-file-label" for="validatedCustomFile">Choose an image</label>
				</div>
				<div class="col-6">
					<img id="FileImage" src="#" name="ImgUrlhi" alt="your image" class="img-thumbnail" width="150" />
				</div>
			</div>
		</div>
		<div class="form-group">
			<label class="control-label" for="ImgUrl">Ảnh nhỏ 1:</label>
			<div class="form-row">
				<div class="col-6">
					<input type="file" name="small1" required>
					
				</div>
			</div>
		</div>
		<div class="form-group">
			<label class="control-label" for="ImgUrl">Ảnh nhỏ 2:</label>
			<div class="form-row">
				<div class="col-6">
					<input type="file" name="small2" required>
				</div>
			</div>
		</div>
		<div class="form-group">
			<label class="control-label" for="ImgUrl">Ảnh nhỏ 3:</label>
			<div class="form-row">
				<div class="col-6">
					<input type="file"  name="small3" required>
				</div>
			</div>
		</div>
		<div class="form-group form-check">
			@Html.EditorFor(model => model.IsActive)
			<label class="form-check-label" for="IsActive">Is Active?</label>
			@Html.ValidationMessageFor(m => m.IsActive, "", new { @class = "text-danger" })
		</div>
		<div class="form-group">
			<input type="submit" class="btn btn-primary" value="Add" />
			<a href="/Admin/WatchMangement" class="btn btn-secondary">Cancel</a>
		</div>
	</div>
</form>
@section scripts {
	<script src="~/Assets/js/ckeditor/ckeditor.js"></script>
	<script src="~/Assets/js/ckeditor/ckeditorconfig.js"></script>
	<script src="~/Assets/js/readurl.js"></script>
}

ShopWatchFinal/ShopWatch.WebMvc/Areas/Admin/Views/WatchMangement/Details.cshtml
@using ShopWatch.WebMvc.ViewModels
@model WatchViewModel
@{
	ViewBag.Title = "Details";
	Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
	var result = Model.Promotions.FirstOrDefault(s => (s.StartDate >= DateTime.Now && s.EndDate <= DateTime.Now));
}

<h2>Sản phẩm @Model.WatchName</h2>

<div class="d-flex bg-light">
	<div class="col-md-6">
		<dl class="dl-horizontal">
			<dt>
				Tên sản phẩm
			</dt>
			<dd>
				@Model.WatchName
			</dd>
			<dt>
				Số lượng
			</dt>
			<dd>
				@Model.Quantity
			</dd>
			<dt>
				Thương hiệu
			</dt>
			<dd>
				@Model.Publisher.PublisherName
			</dd>
			<dt>
				Đơn giá
			</dt>
			<dd>
				@String.Format("{0:0,0}", Model.Price) VNĐ
			</dd>
			<dt>
				Đơn giá khuyến mãi
			</dt>
			<dd>
				@String.Format("{0:0,0}", Model.PricePromotion) VNĐ
			</dd>
			<dt>
				Tạo ngày
			</dt>
			<dd>
				@Model.CreatedDate.ToString("dd/MM/yyyy hh:mm:ss")
			</dd>
			<dt>
				Sửa ngày
			</dt>
			<dd>
				@Model.ModifiedDate.ToString("dd/MM/yyyy hh:mm:ss")
			</dd>
			<dt>
				Đã bán
			</dt>
			<dd>
				@Model.OrderDetails.Sum(s => s.Quantity)
			</dd>
			<dt>
				Tổng tiền đã bán
			</dt>
			<dd>
				@String.Format("{0:0,0}", Model.OrderDetails.Sum(s => (s.Quantity * s.UnitPrice))) VNĐ

			</dd>
			<dt>
				Khuyến mãi đang áp dụng:
			</dt>
			<dd>
				@if(result==null)
				{
					<span class="text-danger">Không có </span>
					<br />
					<a class="btn btn-outline-danger" href="/Admin/WatchPromotionManagement/AddWatchPromotion">Thêm</a>
				}
				else
				{
					<span>@result.PromotionName</span>
				}
			</dd>
		</dl>
		<a href="/Admin/WatchMangement" class="btn btn-secondary">Cancel</a>
	</div>
	<div class="col-md-6">
		<dl class="dl-horizontal">

			<dt>
				Hình Lớn
			</dt>
			<dd>
				<img src="~/Assets/images/HINHLON/@Model.ImageUrl" width="50%" height="50%" />
			</dd>
			<dt>
				Hình Nhỏ
			</dt>
			<dd>
				<img src="~/Assets/images/HINHNHO/@Model.SmallImage/1.jpg" width="120" height="120" /> 
				<img src="~/Assets/images/HINHNHO/@Model.SmallImage/2.jpg" width="120" height="120" /> 
				<img src="~/Assets/images/HINHNHO/@Model.SmallImage/3.jpg" width="120" height="120" />
			</dd>
			<dt>
				Mô tả
			</dt>
			<dd>
				<p>
					@Html.Raw(Model.Description)
				</p>
			</dd>
			<dt>
				Loại sản phẩm
			</dt>
			<dd>
				@Model.Category.CategoryName
			</dd>
			<dt>
				Đánh giá
			</dt>
			<dd>
				@Model.Evaluate
			</dd>
		</dl>
	</div>
	
</div>

ShopWatchFinal/ShopWatch.WebMvc/Areas/Admin/Views/WatchMangement/EditWatch.cshtml
@using ShopWatch.Model
@model Watch
@{ ViewBag.Title = "AddWatch";
	Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml"; }
<h2>Edit Watch</h2>
<hr />
<form action="/Admin/WatchMangement/EditWatch" method="post" class="row form-horizontal" enctype="multipart/form-data">
	@Html.AntiForgeryToken()
	<div class="col">
		<div class="form-group">
			<label name="Name" class="control-label">Watch Name:</label>
			<div>
				<input type="text" name="WatchName" class="form-control" value="@Model.WatchName" required />
				@Html.ValidationMessageFor(m => m.WatchName, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			<label class="control-label">Description:</label>
			<div>
				<textarea class="form-control" name="Description" id="ckeditor" required>@Model.Description</textarea>
				@Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			<label class="control-label">Evaluate:</label>
			<div>
				<textarea class="form-control" name="Evaluate" id="ckeditor" required>@Model.Evaluate</textarea>
				@Html.ValidationMessageFor(m => m.Evaluate, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			<label class="control-label">Price:</label>
			<div>
				<input type="number" class="form-control" name="Price" min="1" value="@Model.Price" required />
				@Html.ValidationMessageFor(m => m.Price, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			<label class="control-label">Quantity:</label>
			<div>
				<input type="number" class="form-control" name="Quantity" min="1" value="@Model.Quantity" required />
				@Html.ValidationMessageFor(m => m.Quantity, "", new { @class = "text-danger" })
			</div>
		</div>
	</div>
	<div class="col">
		<div class="form-group">
			<label class="control-label">Watch Id</label>
			<div>
				<input type="text" name="WatchId" class="form-control" value="@Model.WatchId" readonly="readonly" />
				@Html.ValidationMessageFor(m => m.WatchId, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			<label class="control-label">Category:</label>
			<div class="input-group mb-3">
				@Html.DropDownListFor(model => model.CategoryId, (IEnumerable<SelectListItem>)ViewBag.Categories, htmlAttributes: new { @class = "form-control" })
			</div>
		</div>

		<div class="form-group">
			<label class="control-label">Publisher:</label>
			<div class="input-group mb-3">
				@Html.DropDownListFor(model => model.PublisherId, (IEnumerable<SelectListItem>)ViewBag.Publishers, htmlAttributes: new { @class = "form-control" })

			</div>
		</div>

		<div class="form-group">
			<label class="control-label" for="ImgUrl">Image:</label>
			<div class="form-row">
				<div class="col-6">
					<input type="file" class="custom-file-input" id="validatedCustomFile" name="Img" onchange="readURL(this)">
					<label class="custom-file-label" for="validatedCustomFile">Choose an image</label>
				</div>
				<div class="col-6">
					<img id="FileImage" src="~/Assets/images/HINHLON/@Model.ImageUrl" name="ImgUrlhi" alt="your image" class="img-thumbnail" width="150" />
				</div>
			</div>
		</div>
		<div class="form-group">
			<label class="control-label" for="ImgUrl">Ảnh nhỏ 1:</label>
			<div class="form-row">
				<div class="col-6">
					<input type="file" name="small1">

				</div>
			</div>
		</div>
		<div class="form-group">
			<label class="control-label" for="ImgUrl">Ảnh nhỏ 2:</label>
			<div class="form-row">
				<div class="col-6">
					<input type="file" name="small2" >
				</div>
			</div>
		</div>
		<div class="form-group">
			<label class="control-label" for="ImgUrl">Ảnh nhỏ 3:</label>
			<div class="form-row">
				<div class="col-6">
					<input type="file" name="small3">
				</div>
			</div>
		</div>
		<div class="form-group form-check">
			@Html.EditorFor(model => model.IsActive)
			<label class="form-check-label" for="IsActive">Is Active?</label>
			@Html.ValidationMessageFor(m => m.IsActive, "", new { @class = "text-danger" })
		</div>
		<div class="form-group">
			<input type="submit" class="btn btn-primary" value="Save" />
			<a href="/Admin/WatchMangement" class="btn btn-secondary">Cancel</a>
		</div>
	</div>
</form>
@section scripts {
	<script src="~/Assets/js/ckeditor/ckeditor.js"></script>
	<script src="~/Assets/js/ckeditor/ckeditorconfig.js"></script>
	<script src="~/Assets/js/readurl.js"></script>
}

ShopWatchFinal/ShopWatch.WebMvc/Areas/Admin/Views/WatchMangement/Index.cshtml
@using ShopWatch.BussinessLogicLayer
@using ShopWatch.Model
@using System.Globalization
@model PaginatedList<Watch>
@{
	ViewBag.Title = "Watch management";
	Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<h2>Watch Management</h2>
<hr />
<div>
	<a href="@Url.Action("AddWatch", "WatchMangement")" class="btn btn-primary float-left">Thêm sản phẩm</a>
	<form action="@Url.Action("Index", "WatchMangement")" method="get" class="form-inline float-right">
		<div class="form-group mx-sm-3 mb-2">
			<label for="inputSearch" class="control-label mr-3">Input: </label>
			<input type="text" class="form-control mr-3" id="inputSearch" name="searchString" value="@ViewData["CurrentFilter"]" placeholder="Input....">
			<input type="submit" class=" form-control btn btn-primary mr-3" value="Search" /> |
			<a href="/Admin/WatchMangement/Index" class="btn btn-default">Back to Full List</a>
		</div>
	</form>
</div>
@if (!Model.Any())
{
	<tr><td colspan="3" class="text-center">Don't have any thing.</td></tr> }
else
{
	<nav aria-label="Page navigation example">
		<ul class="pagination justify-content-center">
			@{ var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
				var nextDisabled = !Model.HasNextPage ? "disabled" : "";
				ViewBag.PageRange = 3; }
			<li class="page-item">
				<a href="@Url.Action("Index", "WatchMangement", new { sortOrder=ViewData["CurrentSort"], page=1, currentFilter=ViewData["CurrentFilter"] })"
				   class="btn page-link @prevDisabled"><<</a>
			<li class="page-item">
				<a href="@Url.Action("Index", "WatchMangement", new { sortOrder=ViewData["CurrentSort"], page=(Model.PageIndex - 1 <= 0 ? 1 : Model.PageIndex - 1), currentFilter=ViewData["CurrentFilter"] })"
				   class="btn page-link @prevDisabled"><</a>
			</li>
			@for (int i = 1; i <= Model.TotalPages; i++)
			{
				if (i >= Model.PageIndex - ViewBag.PageRange && i <= Model.PageIndex + ViewBag.PageRange)
				{
					<li class="page-item">
						<a class="@(i==Model.PageIndex ? "Current" : "") page-link"
						   href="@Url.Action("Index", "WatchMangement", new { sortOrder=ViewData["CurrentSort"], page=i, currentFilter=ViewData["CurrentFilter"] })">@i</a>
					</li>
				}
			}
			<li class="page-item">
				<a href="@Url.Action("Index", "WatchMangement", new { sortOrder=ViewData["CurrentSort"], page=(Model.PageIndex + 1 > Model.TotalPages ? Model.TotalPages : Model.PageIndex + 1), currentFilter=ViewData["CurrentFilter"] })"
				   class="btn page-link @nextDisabled">></a>
			<li class="page-item">
				<a href="@Url.Action("Index", "WatchMangement", new { sortOrder=ViewData["CurrentSort"], page=(Model.TotalPages), currentFilter=ViewData["CurrentFilter"] })"
				   class="btn page-link @nextDisabled">>></a>
		</ul>
	</nav>
	<label>Số sản phẩm :@Model.Count</label>
	<table class="table table-condensed table-bordered">
		<tr class="d-flex">
			<th class="col-md-2 text-center">Image</th>
			<th class="col-md-3 text-center">
				<a href="@Url.Action("Index", "WatchMangement", new { sortOrder = ViewData["NameSortParm"], currentFilter = ViewData["CurrentFilter"] })">Watch Name</a>
			</th>
			<th class="col-md-2 text-center">
				<a href="@Url.Action("Index", "WatchMangement", new { sortOrder = ViewData["PriceSortParm"], currentFilter = ViewData["CurrentFilter"] })">Price</a>
			</th>
			<th class="col-md-2 text-center">
				<a href="@Url.Action("Index", "WatchMangement", new { sortOrder = ViewData["PricePromotionSortParm"], currentFilter = ViewData["CurrentFilter"] })">Price Promotion</a>
			</th>
			
			<th class="col-md-1 text-center">
				<a href="@Url.Action("Index", "WatchMangement", new { sortOrder = ViewData["QuantitySortParm"], currentFilter = ViewData["CurrentFilter"] })">Quantity</a>
			</th>
			<th class="col-md-1 text-center">Is Active</th>
			<th class="col-md-1 text-center">Manage</th>
		</tr>

		@foreach (var watch in Model)
		{
			<tr class="d-flex">
				<td class="col-md-2 text-center">
					<img style="max-width:150px; max-height:100px;" src="~/Assets/images/HINHLON/@watch.ImageUrl" alt="@watch.WatchName" />
				</td>
				<td class="col-md-3 text-center ">
					<a href="@Url.Action("Details", "WatchMangement", new { id = watch.WatchId, area = "Admin" })">@watch.WatchName</a>
				</td>
				<td class="col-md-2 text-right">
					@watch.Price.ToString("C0", CultureInfo.CreateSpecificCulture("vi-VN"))
				</td>
				<td class="col-md-2 text-right">
					@watch.PricePromotion.ToString("C0", CultureInfo.CreateSpecificCulture("vi-VN"))
				</td>
				<td class="col-md-1 text-center">
					@watch.Quantity
					<br />
					@if (watch.Quantity == 0)
					{
						<div class="text-danger ">Đã hết </div>
					}
					else if (watch.Quantity < 10)
					{
						<span class="text-warning">Sắp hết </span>
					}
					<br />
					<span>Đã bán @watch.OrderDetails.Sum(s=>s.Quantity)</span>
				</td>
				<td class="col-md-1 text-center">
					@watch.IsActive
				</td>
				<td class="col-md-1">
					<form action="@Url.Action("DeleteWatch","WatchMangement", new { id=watch.WatchId })" method="post">
						<a href="@Url.Action("EditWatch","WatchMangement", new { id=watch.WatchId })" class="btn btn-primary">Edit</a>
						<button type="submit" onclick="return confirm('Bạn chắc muốn xóa sản phẩm này?');" class="btn btn-danger">Delete</button>
					</form>
				</td>
			</tr>
		}
	</table>
}